fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix : /{_locale}/
tareas:
    resource: "@AppBundle/Resources/config/routing.yml"
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
